version: "3.9"
services:
  server:
    build: .
    ports:
      - "8686:8686"
    environment:
      - DATABASE=postgresql://postgres@database/postgres?sslmode=disable
    restart: on-failure
    depends_on:
      - database

  database:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: