// Code generated by ent, DO NOT EDIT.

package flaw

const (
	// Label holds the string label denoting the flaw type in the database.
	Label = "flaw"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the flaw in the database.
	Table = "flaws"
)

// Columns holds all SQL columns for flaw fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "flaws"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_note_flows",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
