// Code generated by ent, DO NOT EDIT.

package ent

import (
	"carlord/ent/billing"
	"carlord/ent/booking"
	"carlord/ent/car"
	"carlord/ent/predicate"
	"carlord/ent/user"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BookingQuery is the builder for querying Booking entities.
type BookingQuery struct {
	config
	limit       *int
	offset      *int
	unique      *bool
	order       []OrderFunc
	fields      []string
	predicates  []predicate.Booking
	withUser    *UserQuery
	withCar     *CarQuery
	withBilling *BillingQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BookingQuery builder.
func (bq *BookingQuery) Where(ps ...predicate.Booking) *BookingQuery {
	bq.predicates = append(bq.predicates, ps...)
	return bq
}

// Limit adds a limit step to the query.
func (bq *BookingQuery) Limit(limit int) *BookingQuery {
	bq.limit = &limit
	return bq
}

// Offset adds an offset step to the query.
func (bq *BookingQuery) Offset(offset int) *BookingQuery {
	bq.offset = &offset
	return bq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bq *BookingQuery) Unique(unique bool) *BookingQuery {
	bq.unique = &unique
	return bq
}

// Order adds an order step to the query.
func (bq *BookingQuery) Order(o ...OrderFunc) *BookingQuery {
	bq.order = append(bq.order, o...)
	return bq
}

// QueryUser chains the current query on the "user" edge.
func (bq *BookingQuery) QueryUser() *UserQuery {
	query := &UserQuery{config: bq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(booking.Table, booking.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, booking.UserTable, booking.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCar chains the current query on the "car" edge.
func (bq *BookingQuery) QueryCar() *CarQuery {
	query := &CarQuery{config: bq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(booking.Table, booking.FieldID, selector),
			sqlgraph.To(car.Table, car.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, booking.CarTable, booking.CarColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBilling chains the current query on the "billing" edge.
func (bq *BookingQuery) QueryBilling() *BillingQuery {
	query := &BillingQuery{config: bq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(booking.Table, booking.FieldID, selector),
			sqlgraph.To(billing.Table, billing.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, booking.BillingTable, booking.BillingColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Booking entity from the query.
// Returns a *NotFoundError when no Booking was found.
func (bq *BookingQuery) First(ctx context.Context) (*Booking, error) {
	nodes, err := bq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{booking.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bq *BookingQuery) FirstX(ctx context.Context) *Booking {
	node, err := bq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Booking ID from the query.
// Returns a *NotFoundError when no Booking ID was found.
func (bq *BookingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{booking.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bq *BookingQuery) FirstIDX(ctx context.Context) int {
	id, err := bq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Booking entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Booking entity is found.
// Returns a *NotFoundError when no Booking entities are found.
func (bq *BookingQuery) Only(ctx context.Context) (*Booking, error) {
	nodes, err := bq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{booking.Label}
	default:
		return nil, &NotSingularError{booking.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bq *BookingQuery) OnlyX(ctx context.Context) *Booking {
	node, err := bq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Booking ID in the query.
// Returns a *NotSingularError when more than one Booking ID is found.
// Returns a *NotFoundError when no entities are found.
func (bq *BookingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{booking.Label}
	default:
		err = &NotSingularError{booking.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bq *BookingQuery) OnlyIDX(ctx context.Context) int {
	id, err := bq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Bookings.
func (bq *BookingQuery) All(ctx context.Context) ([]*Booking, error) {
	if err := bq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return bq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (bq *BookingQuery) AllX(ctx context.Context) []*Booking {
	nodes, err := bq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Booking IDs.
func (bq *BookingQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := bq.Select(booking.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bq *BookingQuery) IDsX(ctx context.Context) []int {
	ids, err := bq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bq *BookingQuery) Count(ctx context.Context) (int, error) {
	if err := bq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return bq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (bq *BookingQuery) CountX(ctx context.Context) int {
	count, err := bq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bq *BookingQuery) Exist(ctx context.Context) (bool, error) {
	if err := bq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return bq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (bq *BookingQuery) ExistX(ctx context.Context) bool {
	exist, err := bq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BookingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bq *BookingQuery) Clone() *BookingQuery {
	if bq == nil {
		return nil
	}
	return &BookingQuery{
		config:      bq.config,
		limit:       bq.limit,
		offset:      bq.offset,
		order:       append([]OrderFunc{}, bq.order...),
		predicates:  append([]predicate.Booking{}, bq.predicates...),
		withUser:    bq.withUser.Clone(),
		withCar:     bq.withCar.Clone(),
		withBilling: bq.withBilling.Clone(),
		// clone intermediate query.
		sql:    bq.sql.Clone(),
		path:   bq.path,
		unique: bq.unique,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BookingQuery) WithUser(opts ...func(*UserQuery)) *BookingQuery {
	query := &UserQuery{config: bq.config}
	for _, opt := range opts {
		opt(query)
	}
	bq.withUser = query
	return bq
}

// WithCar tells the query-builder to eager-load the nodes that are connected to
// the "car" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BookingQuery) WithCar(opts ...func(*CarQuery)) *BookingQuery {
	query := &CarQuery{config: bq.config}
	for _, opt := range opts {
		opt(query)
	}
	bq.withCar = query
	return bq
}

// WithBilling tells the query-builder to eager-load the nodes that are connected to
// the "billing" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BookingQuery) WithBilling(opts ...func(*BillingQuery)) *BookingQuery {
	query := &BillingQuery{config: bq.config}
	for _, opt := range opts {
		opt(query)
	}
	bq.withBilling = query
	return bq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		StartAt time.Time `json:"start_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Booking.Query().
//		GroupBy(booking.FieldStartAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bq *BookingQuery) GroupBy(field string, fields ...string) *BookingGroupBy {
	grbuild := &BookingGroupBy{config: bq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return bq.sqlQuery(ctx), nil
	}
	grbuild.label = booking.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		StartAt time.Time `json:"start_at,omitempty"`
//	}
//
//	client.Booking.Query().
//		Select(booking.FieldStartAt).
//		Scan(ctx, &v)
func (bq *BookingQuery) Select(fields ...string) *BookingSelect {
	bq.fields = append(bq.fields, fields...)
	selbuild := &BookingSelect{BookingQuery: bq}
	selbuild.label = booking.Label
	selbuild.flds, selbuild.scan = &bq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a BookingSelect configured with the given aggregations.
func (bq *BookingQuery) Aggregate(fns ...AggregateFunc) *BookingSelect {
	return bq.Select().Aggregate(fns...)
}

func (bq *BookingQuery) prepareQuery(ctx context.Context) error {
	for _, f := range bq.fields {
		if !booking.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bq.path != nil {
		prev, err := bq.path(ctx)
		if err != nil {
			return err
		}
		bq.sql = prev
	}
	return nil
}

func (bq *BookingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Booking, error) {
	var (
		nodes       = []*Booking{}
		withFKs     = bq.withFKs
		_spec       = bq.querySpec()
		loadedTypes = [3]bool{
			bq.withUser != nil,
			bq.withCar != nil,
			bq.withBilling != nil,
		}
	)
	if bq.withUser != nil || bq.withCar != nil || bq.withBilling != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, booking.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Booking).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Booking{config: bq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bq.withUser; query != nil {
		if err := bq.loadUser(ctx, query, nodes, nil,
			func(n *Booking, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := bq.withCar; query != nil {
		if err := bq.loadCar(ctx, query, nodes, nil,
			func(n *Booking, e *Car) { n.Edges.Car = e }); err != nil {
			return nil, err
		}
	}
	if query := bq.withBilling; query != nil {
		if err := bq.loadBilling(ctx, query, nodes, nil,
			func(n *Booking, e *Billing) { n.Edges.Billing = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bq *BookingQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*Booking, init func(*Booking), assign func(*Booking, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Booking)
	for i := range nodes {
		if nodes[i].booking_user == nil {
			continue
		}
		fk := *nodes[i].booking_user
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "booking_user" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (bq *BookingQuery) loadCar(ctx context.Context, query *CarQuery, nodes []*Booking, init func(*Booking), assign func(*Booking, *Car)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Booking)
	for i := range nodes {
		if nodes[i].booking_car == nil {
			continue
		}
		fk := *nodes[i].booking_car
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(car.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "booking_car" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (bq *BookingQuery) loadBilling(ctx context.Context, query *BillingQuery, nodes []*Booking, init func(*Booking), assign func(*Booking, *Billing)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Booking)
	for i := range nodes {
		if nodes[i].billing_booking == nil {
			continue
		}
		fk := *nodes[i].billing_booking
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(billing.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "billing_booking" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (bq *BookingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bq.querySpec()
	_spec.Node.Columns = bq.fields
	if len(bq.fields) > 0 {
		_spec.Unique = bq.unique != nil && *bq.unique
	}
	return sqlgraph.CountNodes(ctx, bq.driver, _spec)
}

func (bq *BookingQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := bq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (bq *BookingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   booking.Table,
			Columns: booking.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: booking.FieldID,
			},
		},
		From:   bq.sql,
		Unique: true,
	}
	if unique := bq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := bq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, booking.FieldID)
		for i := range fields {
			if fields[i] != booking.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bq *BookingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bq.driver.Dialect())
	t1 := builder.Table(booking.Table)
	columns := bq.fields
	if len(columns) == 0 {
		columns = booking.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bq.sql != nil {
		selector = bq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bq.unique != nil && *bq.unique {
		selector.Distinct()
	}
	for _, p := range bq.predicates {
		p(selector)
	}
	for _, p := range bq.order {
		p(selector)
	}
	if offset := bq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BookingGroupBy is the group-by builder for Booking entities.
type BookingGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bgb *BookingGroupBy) Aggregate(fns ...AggregateFunc) *BookingGroupBy {
	bgb.fns = append(bgb.fns, fns...)
	return bgb
}

// Scan applies the group-by query and scans the result into the given value.
func (bgb *BookingGroupBy) Scan(ctx context.Context, v any) error {
	query, err := bgb.path(ctx)
	if err != nil {
		return err
	}
	bgb.sql = query
	return bgb.sqlScan(ctx, v)
}

func (bgb *BookingGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range bgb.fields {
		if !booking.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := bgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (bgb *BookingGroupBy) sqlQuery() *sql.Selector {
	selector := bgb.sql.Select()
	aggregation := make([]string, 0, len(bgb.fns))
	for _, fn := range bgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(bgb.fields)+len(bgb.fns))
		for _, f := range bgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(bgb.fields...)...)
}

// BookingSelect is the builder for selecting fields of Booking entities.
type BookingSelect struct {
	*BookingQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bs *BookingSelect) Aggregate(fns ...AggregateFunc) *BookingSelect {
	bs.fns = append(bs.fns, fns...)
	return bs
}

// Scan applies the selector query and scans the result into the given value.
func (bs *BookingSelect) Scan(ctx context.Context, v any) error {
	if err := bs.prepareQuery(ctx); err != nil {
		return err
	}
	bs.sql = bs.BookingQuery.sqlQuery(ctx)
	return bs.sqlScan(ctx, v)
}

func (bs *BookingSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(bs.fns))
	for _, fn := range bs.fns {
		aggregation = append(aggregation, fn(bs.sql))
	}
	switch n := len(*bs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		bs.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		bs.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := bs.sql.Query()
	if err := bs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
