# This is a basic workflow that is manually triggered

name: deployment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - CAR-15
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Docker-Compose Remote Deployment
        # You may pin to the exact commit or the version.
        # uses: TapTap21/docker-remote-deployment-action@25d2611b060f7a53f19d4e5bad42a2fb2c4a7a80
        uses: TapTap21/docker-remote-deployment-action@v1.1
        with:
          # Remote Docker host ie (user@host)
          remote_docker_host: ${{secrets.SERVER}}
          # Remote Docker SSH public key
          ssh_public_key: ${{secrets.PUBLIC_KEY}}
          # SSH private key used to connect to the docker host
          ssh_private_key: ${{secrets.DEPLOY_KEY}}
          args: up -d

