name: deployment
on:
  push:
    branches:
      - CAR-15

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{secrets.HOOK_URL}}
          method: 'GET'